services:

  drupal_injection_callback:
    class: D7ServiceContainer\DrupalInjectionCallback
    public: yes
    autoconfigure: yes
    autowire: yes


  drupal_callback_abstract:
    class: D7ServiceContainer\CallbackServiceRepresentation
    abstract: true
    arguments:
      - n_a
      - n_a
      - n_a
      - n_a
      - n_a
      - n_a
      - n_a
      - n_a
      - n_a
